### ISSUE TITLE
H2 Pooling configuration

### ISSUE THREAD

**Issue by cemo** [r2dbc/r2dbc-pool#133]
## Bug Report

This is the relevant section of my configuration to create h2 pool for testing. It is working against PostgreSQL but not for H2. H2 requires mem or file settings by protocol but setting it overriding options.

```
r2dbc:
  datasources:
    default:
      options:
        driver: pool
        protocol: h2
      url: r2dbc:h2:mem:///testdb-r2dbc=-1
      username: sa
      password: ''
      dialect: h2
```
#### Versions

- Driver: Pooling Driver
- Database: h2
- Java: 16
- OS: MacOs

#### Steps to reproduce

I tried like this too but I could not figure out it too.

```java
        ConnectionFactories.get(ConnectionFactoryOptions.builder()
                                                        .option(DRIVER, "pool")
                                                        .option(PROTOCOL, "h2")
                                                        .option(HOST, "")
                                                        .option(USER, "sa")
                                                        .option(PASSWORD, "")
                                                        .option(DATABASE, "Testmem")
                                                        .build());
```
